
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.kkarasavvas.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

#force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Kostas A. Karasavvas"
title: "{ Kostas A. Karasavvas }"
description: "Software Architect and Engineer, Bitcoin and Blockchain Consultant, Researcher, Educator"
keywords: "kostas, konstantinos, karasavvas, personal, software, architect, engineer, developer, consultant, bitcoin, blockchain, cryptocurrencies, researcher, educator"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 3500
lines: # You can add HTML Tags in the Text
  - text: "Software Architect and Engineer"
  - text: "Bitcoin and Open Blockchains"
  - text: "Open Source Contributor"
  - text: "Researcher and Educator"

me-img: "/img/kkarasavvas3-small-square.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

#disqus-shortname: "kkarasavvas"

syntax-highlight: True

############
# Projects #
############

#projects:
#  - image: "/img/timeline/webDevelopment.png"
#    title: "Raising Blockchain technology awareness"
#    description: "Web development"
#  - image: "/img/timeline/softwareArchitecture.png"
#    title: "Bitcoin applications"
#    description: "Software architecture, design, engineering, management"
#  - image: "/img/timeline/softwareArchitecture.png"
#    title: "Workflow technology"
#    description: "Software architecture, design, engineering, management"
#  - image: "/img/timeline/softwareArchitecture.png"
#    title: "Distributed data access and management"
#    description: "Software architecture, design, engineering, management"
#  - image: "/img/timeline/softwareArchitecture.png"
#    title: "Old projects"
#    description: "Software architecture, design, engineering, management"

############
# Timeline #
############

events:
  - image: "/img/timeline/bitcoinConsultant.png"
    date: "Jan 2013 - Today"
    description: "Bitcoin engineer, open source contributor, researcher and educator"
  - image: "/img/timeline/softwareArchitecture.png"
    date: "Aug 2010 - Today"
    description: "Software architecture, design, engineering, management"
  - image: "/img/timeline/lecturer1.png"
    date: "Sep 2008 - Today"
    description: "Lecturer<br/>(part-time)"
  - image: "/img/timeline/rnd2.png"
    date: "Jun 2004 - July 2012"
    description: "R&D: workflow technology, data integration/streaming, web development" 
  - image: "/img/timeline/lecturer2.jpg"
    date: "Mar 1999 - Jun 2004"
    description: "Lecturer assistant<br/>(part-time)"
  - image: "/img/timeline/rnd1.png"
    date: "Oct 1997 - Jun 2004"
    description: "R&D: distributed computing and multi-agent systems"
  - image: "/img/timeline/webDevelopment.png"
    date: "Feb 1996 - Sep 1997"
    description: "Web development"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "kkarasavvas@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "Dr. Konstantinos Karasavvas is a computer scientist with 20+ years of experience. For the last 7 years, he is focused solely on Bitcoin and open blockchain technologies. He is teaching and leading several research and development teams in both academia and industry. He is also an open source contributor and an active member of local Bitcoin communities, organizing meetups and presenting in events."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/kkarasavvas"
    tooltip: "Twitter"
  - title: "github"
    url: "https://github.com/karask"
    tooltip: "Github"
  - title: "linkedin"
    url: "https://gr.linkedin.com/in/kkarasavvas"
    tooltip: "LinkedIn"
  - title: "users"
    url: "http://www.meetup.com/BlockchainGreece-1"
    tooltip: "Meetup"
#  - title: "facebook"
#    url: "https://facebook.com/"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: kkarasavvas
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'projects'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Talks: 'talks'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts" ]
#exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "latest-post.html", "_posts", "blog" ]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

plugins: [jekyll-paginate]
